export interface DataType {
    key: string;
    name: string;
    age: number;
    address: string;
    product: string;
    price: number;
    tags: string[];
    description: string;
    category: string;
    rating: number;
    stock: number;
    sku: string;
    brand: string;
}



export const data: DataType[] = [
    {
        key: "1",
        name: "John Brown",
        age: 32,
        address: "New York No. 1 Lake Park",
        product: "Wireless Mouse",
        price: 799,
        tags: ["successful"],
        description: "A compact wireless mouse with smooth tracking and long battery life, ideal for everyday office use.",
        category: "Accessories",
        rating: 4.5,
        stock: 120,
        sku: "WM-1001",
        brand: "LogiTech",
    },
    {
        key: "2",
        name: "Jim Green",
        age: 42,
        address: "London No. 1 Lake Park",
        product: "Mechanical Keyboard",
        price: 3499,
        tags: ["active"],
        description: "A mechanical keyboard with tactile switches, backlit keys, and a durable aluminum frame.",
        category: "Accessories",
        rating: 4.7,
        stock: 45,
        sku: "KB-2044",
        brand: "KeyPro",
    },
    {
        key: "3",
        name: "Joe Black",
        age: 28,
        address: "Sydney No. 1 Lake Park",
        product: "USB-C Cable",
        price: 299,
        tags: ["new"],
        description: "A fast-charging USB-C cable with reinforced connectors and tangle-free design.",
        category: "Cables",
        rating: 4.1,
        stock: 300,
        sku: "CB-7781",
        brand: "CableMax",
    },
    {
        key: "4",
        name: "Alice White",
        age: 35,
        address: "Toronto No. 2 Lake Park",
        product: "Laptop Stand",
        price: 1299,
        tags: ["successful"],
        description: "An ergonomic aluminum laptop stand that improves posture and keeps your desk organized.",
        category: "Office",
        rating: 4.3,
        stock: 80,
        sku: "LS-3320",
        brand: "ErgoLift",
    },
    {
        key: "5",
        name: "Michael Smith",
        age: 30,
        address: "California No. 3 Lake Park",
        product: "Bluetooth Headphones",
        price: 2499,
        tags: ["popular"],
        description: "Wireless headphones with deep bass, clear vocals, and up to 20 hours of battery life.",
        category: "Audio",
        rating: 4.6,
        stock: 60,
        sku: "BH-9912",
        brand: "SoundBeat",
    },
    {
        key: "6",
        name: "Sarah Johnson",
        age: 27,
        address: "Berlin No. 4 Lake Park",
        product: "Webcam",
        price: 1899,
        tags: ["active"],
        description: "A full HD webcam with built-in microphone, perfect for video calls and online meetings.",
        category: "Video",
        rating: 4.2,
        stock: 90,
        sku: "WC-5567",
        brand: "CamPro",
    },
    {
        key: "7",
        name: "David Lee",
        age: 41,
        address: "Seoul No. 5 Lake Park",
        product: "Portable SSD 1TB",
        price: 7499,
        tags: ["premium"],
        description: "High-speed portable SSD with 1TB storage, offering fast transfers and reliable performance.",
        category: "Storage",
        rating: 4.8,
        stock: 25,
        sku: "SSD-1TB-77",
        brand: "FastDisk",
    },
    {
        key: "8",
        name: "Emma Wilson",
        age: 29,
        address: "Paris No. 6 Lake Park",
        product: "Smartphone Charger",
        price: 999,
        tags: ["new"],
        description: "A compact fast charger compatible with most smartphones and tablets.",
        category: "Chargers",
        rating: 4.0,
        stock: 200,
        sku: "CH-2233",
        brand: "ChargeIt",
    },
    {
        key: "9",
        name: "Chris Martin",
        age: 34,
        address: "Paris No. 6 Lake Park",
        product: "Product",
        price: 400,
        tags: ["premium"],
        description: "An unknown product with no details available.",
        category: "Chargers",
        rating: 4.5,
        stock: 400,
        sku: "NA-0000",
        brand: "RealMe",
    },
    {
        key: "10",
        name: "Olivia Taylor",
        age: 26,
        address: "Amsterdam No. 8 Lake Park",
        product: "Desk Lamp",
        price: 1199,
        tags: ["active"],
        description: "An LED desk lamp with adjustable brightness and color temperature for comfortable reading.",
        category: "Lighting",
        rating: 4.4,
        stock: 70,
        sku: "DL-9081",
        brand: "BrightLite",
    },
    {
        key: "11",
        name: "Daniel Anderson",
        age: 38,
        address: "Oslo No. 9 Lake Park",
        product: "Gaming Mouse Pad",
        price: 499,
        tags: ["budget"],
        description: "A large, smooth-surface mouse pad designed for precise and consistent mouse movements.",
        category: "Accessories",
        rating: 4.1,
        stock: 180,
        sku: "MP-3301",
        brand: "PlayGear",
    },
    {
        key: "12",
        name: "Sophia Thomas",
        age: 31,
        address: "Rome No. 10 Lake Park",
        product: "External Hard Drive 2TB",
        price: 6299,
        tags: ["premium"],
        description: "A 2TB external hard drive for backups, media storage, and file transfers.",
        category: "Storage",
        rating: 4.6,
        stock: 40,
        sku: "HD-2TB-88",
        brand: "StoreMax",
    },
    {
        key: "13",
        name: "James Harris",
        age: 45,
        address: "Madrid No. 11 Lake Park",
        product: "Noise Cancelling Earbuds",
        price: 2999,
        tags: ["successful"],
        description: "Compact earbuds with active noise cancellation and clear, balanced sound.",
        category: "Audio",
        rating: 4.3,
        stock: 65,
        sku: "NE-5542",
        brand: "SoundBeat",
    },
    {
        key: "14",
        name: "Isabella Clark",
        age: 33,
        address: "Vienna No. 12 Lake Park",
        product: "Monitor 24-inch",
        price: 12999,
        tags: ["featured"],
        description: "A 24-inch full HD monitor with slim bezels and vibrant color reproduction.",
        category: "Displays",
        rating: 4.7,
        stock: 30,
        sku: "MN-24FHD",
        brand: "ViewBest",
    },
    {
        key: "15",
        name: "William Lewis",
        age: 36,
        address: "Prague No. 13 Lake Park",
        product: "HDMI Cable",
        price: 399,
        tags: ["budget"],
        description: "A durable HDMI cable supporting high-definition video and audio transmission.",
        category: "Cables",
        rating: 4.0,
        stock: 500,
        sku: "HDMI-201",
        brand: "CableMax",
    },
    {
        key: "16",
        name: "Mia Walker",
        age: 24,
        address: "Zurich No. 14 Lake Park",
        product: "USB Hub",
        price: 899,
        tags: ["new"],
        description: "A multi-port USB hub that expands your laptop connectivity with extra USB ports.",
        category: "Accessories",
        rating: 4.2,
        stock: 140,
        sku: "USBH-778",
        brand: "PortPlus",
    },
    {
        key: "17",
        name: "Benjamin Hall",
        age: 40,
        address: "Stockholm No. 15 Lake Park",
        product: "Office Chair",
        price: 8999,
        tags: ["premium"],
        description: "An ergonomic office chair with adjustable height, lumbar support, and breathable mesh.",
        category: "Furniture",
        rating: 4.5,
        stock: 22,
        sku: "CH-ERG-09",
        brand: "ComfortSeat",
    },
    {
        key: "18",
        name: "Charlotte Young",
        age: 28,
        address: "Helsinki No. 16 Lake Park",
        product: "Laptop Backpack",
        price: 2199,
        tags: ["popular"],
        description: "A lightweight, water-resistant backpack with padded compartments for laptops and accessories.",
        category: "Bags",
        rating: 4.4,
        stock: 75,
        sku: "BP-4402",
        brand: "UrbanCarry",
    },
    {
        key: "19",
        name: "Henry King",
        age: 37,
        address: "Lisbon No. 17 Lake Park",
        product: "Smartwatch",
        price: 5499,
        tags: ["featured"],
        description: "A smartwatch with fitness tracking, notifications, and long-lasting battery life.",
        category: "Wearables",
        rating: 4.6,
        stock: 55,
        sku: "SW-9900",
        brand: "FitTime",
    },
    {
        key: "20",
        name: "Amelia Scott",
        age: 34,
        address: "Copenhagen No. 18 Lake Park",
        product: "Wireless Speaker",
        price: 3299,
        tags: ["successful"],
        description: "A portable wireless speaker with rich sound, deep bass, and all-day battery life.",
        category: "Audio",
        rating: 4.5,
        stock: 85,
        sku: "SP-7701",
        brand: "SoundBeat",
    },
];

