
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ConfigProvider } from "antd";
import "./globals.css";
import { CurrencyProvider } from "@/lib/currencyContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#555555',
              borderRadius: 2,
              colorBgContainer: '#FFFFFF',
            },
            components: {
              Table: {
                headerBg: '#C3CDF4',
                headerColor: '#fff',
              },
            },
          }}
        >
          <CurrencyProvider>
            {children}
          </CurrencyProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
